using System;
using System.Numerics;
using Content.Shared._BaroStation.NuclearReactor;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._BaroStation.NuclearReactor;

[GenerateTypedNameReferences]
public sealed partial class NuclearReactorWindow : DefaultWindow
{
    public event Action<bool>? ToggleReactor;
    public event Action<float>? SetTemperature;
    public event Action<int>? EjectRod;

    private readonly SlotButton[] _slotButtons = new SlotButton[4];
    private NuclearReactorUiState? _lastState;

    public NuclearReactorWindow()
    {
        RobustXamlLoader.Load(this);

        ToggleButton.OnPressed += _ => ToggleReactor?.Invoke(!(_lastState?.Enabled ?? false));
        SetTempButton.OnPressed += _ =>
        {
            if (float.TryParse(TargetTempInput.Text, out var temp))
                SetTemperature?.Invoke(temp);
        };

        for (int i = 0; i < 4; i++)
        {
            var btn = new SlotButton(i);
            btn.OnPressed += _ => EjectRod?.Invoke(btn.SlotIndex);
            _slotButtons[i] = btn;
            RodsGrid.AddChild(btn);
        }
    }

    public void UpdateState(NuclearReactorUiState state)
    {
        _lastState = state;

        StatusLabel.Text = state.Enabled ? "АКТИВЕН" : "ВЫКЛЮЧЕН";
        StatusLabel.SetOnlyStyleClass(state.Enabled ? "LabelCaution" : "LabelSecondaryColor");
        ToggleButton.Text = state.Enabled ? "Выключить" : "Включить";

        int rodCount = 0;
        foreach (var slot in state.RodSlots)
            if (slot.HasItem) rodCount++;

        float optimalTemp = rodCount * 1000f;
        RodCountLabel.Text = $"{rodCount} / 4";
        OptimalTempLabel.Text = $"{optimalTemp:F0} K";

        if (rodCount == 0)
        {
            StateLabel.Text = "Нет стержней";
            StateLabel.SetOnlyStyleClass("LabelSecondaryColor");
        }
        else if (state.CurrentTemperature < optimalTemp - 50)
        {
            StateLabel.Text = "Недостаточная температура";
            StateLabel.SetOnlyStyleClass("LabelCaution");
        }
        else if (state.CurrentTemperature > optimalTemp + 50)
        {
            StateLabel.Text = "ЧРЕЗМЕРНАЯ ТЕМПЕРАТУРА! ПЛАВЛЕНИЕ!";
            StateLabel.SetOnlyStyleClass("LabelDanger");
        }
        else
        {
            StateLabel.Text = "Оптимальный режим";
            StateLabel.SetOnlyStyleClass("LabelGood");
        }

        TemperatureLabel.Text = $"{state.CurrentTemperature:F1} K";
        TemperatureBar.Value = state.CurrentTemperature;
        TemperatureBar.MaxValue = Math.Max(5000, state.CurrentTemperature * 1.2f);
        TargetTempInput.Text = state.TargetTemperature.ToString("F0");

        PowerLabel.Text = $"{state.PowerOutput / 1000f:F1} kW";

        IntegrityLabel.Text = $"{state.Integrity:F0}%";
        if (state.Integrity < 30)
            IntegrityLabel.SetOnlyStyleClass("LabelDanger");
        else if (state.Integrity < 60)
            IntegrityLabel.SetOnlyStyleClass("LabelCaution");
        else
            IntegrityLabel.SetOnlyStyleClass("LabelGood");

        for (int i = 0; i < 4; i++)
        {
            _slotButtons[i].UpdateState(state.RodSlots[i]);
        }

        WarningLabel.Visible = rodCount == 0;
    }

    private sealed class SlotButton : Button
    {
        public int SlotIndex { get; }
        private readonly Label _textLabel;
        private readonly ProgressBar _fuelBar;

        public SlotButton(int index)
        {
            SlotIndex = index;
            MinSize = new Vector2(100, 80);

            var vbox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center
            };

            _textLabel = new Label { Text = "Пусто", HorizontalAlignment = HAlignment.Center };
            _fuelBar = new ProgressBar { MinSize = new Vector2(80, 10), Visible = false };

            vbox.AddChild(_textLabel);
            vbox.AddChild(_fuelBar);
            AddChild(vbox);
        }

        public void UpdateState(ContainerInfo info)
        {
            if (info.HasItem)
            {
                _textLabel.Text = info.ItemName ?? "Стержень";
                if (info.FuelLeft.HasValue)
                {
                    _fuelBar.Visible = true;
                    _fuelBar.Value = info.FuelLeft.Value;
                    if (info.FuelLeft.Value < 0.2f)
                        _fuelBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.Red };
                    else
                        _fuelBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.LimeGreen };
                }
                else
                {
                    _fuelBar.Visible = false;
                }
                Disabled = false;
            }
            else
            {
                _textLabel.Text = $"Слот {SlotIndex + 1}\n(Пусто)";
                _fuelBar.Visible = false;
                Disabled = true;
            }
        }
    }
}
