using System.Numerics;
using Content.Shared._BaroStation.NuclearReactor;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Shared.IoC;
using Robust.Shared.Log;

namespace Content.Client._BaroStation.NuclearReactor;

[GenerateTypedNameReferences]
public sealed partial class NuclearReactorConsoleWindow : DefaultWindow
{
    public event Action<bool>? ToggleReactor;
    public event Action<float>? SetTemperature;
    public event Action<int>? EjectRod;
    public event Action<int>? SetCoolingLevel;
    public event Action? ClearLink;

    private static readonly ISawmill Logger = IoCManager.Resolve<ILogManager>().GetSawmill("nuclear.ui");
    private readonly SlotButton[] _slotButtons = new SlotButton[4];
    private NuclearReactorConsoleUiState? _lastState;
    private PanelContainer _overlayPanel = null!;
    private Label _overlayLabel = null!;

    public NuclearReactorConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        // Создаём оверлей программно
        CreateOverlay();

        ToggleButton.OnPressed += _ => ToggleReactor?.Invoke(!(_lastState?.ReactorEnabled ?? false));
        SetTempButton.OnPressed += _ =>
        {
            if (float.TryParse(TargetTempInput.Text, out var temp))
                SetTemperature?.Invoke(temp);
        };
        CoolingDownButton.OnPressed += _ =>
        {
            var newLevel = (_lastState?.CoolingLevel ?? 1) - 1;
            if (newLevel >= 1)
                SetCoolingLevel?.Invoke(newLevel);
        };
        CoolingUpButton.OnPressed += _ =>
        {
            var newLevel = (_lastState?.CoolingLevel ?? 1) + 1;
            if (newLevel <= 8)
                SetCoolingLevel?.Invoke(newLevel);
        };

        for (int i = 0; i < 4; i++)
        {
            var btn = new SlotButton(i);
            btn.OnPressed += _ => EjectRod?.Invoke(btn.SlotIndex);
            _slotButtons[i] = btn;
            RodsGrid.AddChild(btn);
        }
    }

    private void CreateOverlay()
    {
        _overlayPanel = new PanelContainer
        {
            Name = "OverlayPanel",
            Visible = false,
            MouseFilter = Control.MouseFilterMode.Ignore  // <- Игнорируем клики на оверлее
        };

        var styleBox = new StyleBoxFlat
        {
            BackgroundColor = new Color(0, 0, 0, 0.5f) // #80000000
        };
        _overlayPanel.PanelOverride = styleBox;

        _overlayLabel = new Label
        {
            Text = Loc.GetString("nuclear-reactor-console-not-linked-overlay"),
            FontColorOverride = Color.White,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            MouseFilter = Control.MouseFilterMode.Ignore  // <- И текст игнорирует клики
        };
        _overlayPanel.AddChild(_overlayLabel);

        AddChild(_overlayPanel);
        _overlayPanel.SetPositionLast();

        // Растягиваем оверлей на всё окно
        LayoutContainer.SetAnchorLeft(_overlayPanel, 0);
        LayoutContainer.SetAnchorRight(_overlayPanel, 1);
        LayoutContainer.SetAnchorTop(_overlayPanel, 0);
        LayoutContainer.SetAnchorBottom(_overlayPanel, 1);

        // Отступ сверху (только визуальный, клики всё равно проходят)
        LayoutContainer.SetMarginTop(_overlayPanel, 30);

        // Центрируем текст
        LayoutContainer.SetAnchorLeft(_overlayLabel, 0.5f);
        LayoutContainer.SetAnchorRight(_overlayLabel, 0.5f);
        LayoutContainer.SetAnchorTop(_overlayLabel, 0.5f);
        LayoutContainer.SetAnchorBottom(_overlayLabel, 0.5f);
        LayoutContainer.SetGrowHorizontal(_overlayLabel, LayoutContainer.GrowDirection.Both);
        LayoutContainer.SetGrowVertical(_overlayLabel, LayoutContainer.GrowDirection.Both);
    }

    public void UpdateState(NuclearReactorConsoleUiState state)
    {
        var hasLink = state.HasPower && state.HasReactor;

        if (!hasLink)
        {
            MainContent.Visible = false;
            _overlayPanel.Visible = true;
            return;
        }

        MainContent.Visible = true;
        _overlayPanel.Visible = false;

        try
        {
            _lastState = state;

            // Проверка на null
            if (RodsGrid == null || StatusLabel == null ||
                ToggleButton == null || StateLabel == null || OptimalTempLabel == null ||
                TemperatureLabel == null || TemperatureBar == null || TargetTempInput == null ||
                SetTempButton == null || CoolingDownButton == null || CoolingUpButton == null ||
                CoolingLevelLabel == null || PowerLabel == null || IntegrityLabel == null ||
                DepletedWarningLabel == null || WarningLabel == null)
            {
                Logger.Error("XAML not loaded properly - exiting UpdateState");
                return;
            }

            var hasControl = state.HasPower && state.HasReactor;

            // Управление
            ToggleButton.Disabled = !hasControl;
            SetTempButton.Disabled = !hasControl;
            TargetTempInput.Editable = hasControl && !state.ReactorEnabled;
            CoolingDownButton.Disabled = !hasControl || state.ReactorEnabled || state.CoolingLevel <= 1;
            CoolingUpButton.Disabled = !hasControl || state.ReactorEnabled || state.CoolingLevel >= 8;

            // Статус
            if (!hasControl)
                StatusLabel.Text = !state.HasReactor
                    ? Loc.GetString("nuclear-reactor-console-no-reactor-short")
                    : Loc.GetString("nuclear-reactor-status-inactive");
            else if (state.ReactorEnabled)
                StatusLabel.Text = Loc.GetString("nuclear-reactor-status-active");
            else
                StatusLabel.Text = Loc.GetString("nuclear-reactor-status-inactive");

            ToggleButton.Text = state.ReactorEnabled
                ? Loc.GetString("nuclear-reactor-window-toggle-off")
                : Loc.GetString("nuclear-reactor-window-toggle-on");

            // Подсчёт активных стержней
            int activeRodCount = 0;
            foreach (var slot in state.RodSlots)
                if (slot.HasItem && !slot.Depleted) activeRodCount++;

            OptimalTempLabel.Text = $"{activeRodCount * 1000f:F0} K";
            DepletedWarningLabel.Visible = state.HasDepletedRod;

            // Режим работы
            if (activeRodCount == 0)
            {
                StateLabel.Text = Loc.GetString("nuclear-reactor-mode-no-rods");
                StateLabel.SetOnlyStyleClass("LabelSecondaryColor");
            }
            else
            {
                float optimalMin = state.OptimalTemperature - 300f;
                float optimalMax = state.OptimalTemperature + 300f;

                if (state.CurrentTemperature < optimalMin)
                {
                    StateLabel.Text = Loc.GetString("nuclear-reactor-mode-insufficient", ("min", optimalMin));
                    StateLabel.SetOnlyStyleClass("LabelCaution");
                }
                else if (state.CurrentTemperature > optimalMax)
                {
                    StateLabel.Text = Loc.GetString("nuclear-reactor-mode-excessive", ("max", optimalMax));
                    StateLabel.SetOnlyStyleClass("LabelDanger");
                }
                else
                {
                    StateLabel.Text = Loc.GetString("nuclear-reactor-mode-optimal", ("min", optimalMin), ("max", optimalMax));
                    StateLabel.SetOnlyStyleClass("LabelGood");
                }
            }

            // Данные
            TemperatureLabel.Text = $"{state.CurrentTemperature:F1} K";
            TemperatureBar.Value = state.CurrentTemperature;
            TargetTempInput.Text = state.TargetTemperature.ToString("F0");
            CoolingLevelLabel.Text = state.CoolingLevel.ToString();
            PowerLabel.Text = $"{state.PowerOutput / 1000f:F1} kW";

            // Целостность с цветовой индикацией
            IntegrityLabel.Text = $"{state.Integrity:F0}%";
            if (state.Integrity < 30)
                IntegrityLabel.SetOnlyStyleClass("LabelDanger");
            else if (state.Integrity < 60)
                IntegrityLabel.SetOnlyStyleClass("LabelCaution");
            else
                IntegrityLabel.SetOnlyStyleClass("LabelGood");

            // Обновление слотов стержней
            for (int i = 0; i < 4; i++)
            {
                if (i < state.RodSlots.Length)
                    _slotButtons[i].UpdateState(state.RodSlots[i]);
            }

            WarningLabel.Visible = activeRodCount == 0;
        }
        catch (Exception ex)
        {
            Logger.Error($"Exception in UpdateState: {ex.Message}\n{ex.StackTrace}");
        }
    }

    private sealed class SlotButton : Button
    {
        public int SlotIndex { get; }
        private readonly Label _textLabel;
        private readonly ProgressBar _fuelBar;

        public SlotButton(int index)
        {
            SlotIndex = index;
            MinSize = new Vector2(100, 80);

            var vbox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center
            };

            _textLabel = new Label { Text = "Empty", HorizontalAlignment = HAlignment.Center };
            _fuelBar = new ProgressBar
            {
                MinSize = new Vector2(80, 10),
                Visible = false,
                MinValue = 0,
                MaxValue = 1,
                Value = 0
            };

            vbox.AddChild(_textLabel);
            vbox.AddChild(_fuelBar);
            AddChild(vbox);
        }

        public void UpdateState(ContainerInfo info)
        {
            if (info.HasItem)
            {
                if (info.Depleted)
                {
                    _textLabel.Text = info.ItemName ?? Loc.GetString("nuclear-reactor-rod");
                    _textLabel.FontColorOverride = Color.Red;
                    _fuelBar.Visible = true;
                    _fuelBar.Value = 0;
                    _fuelBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.Gray };
                    Disabled = false;
                }
                else
                {
                    _textLabel.Text = info.ItemName ?? Loc.GetString("nuclear-reactor-rod");
                    _textLabel.FontColorOverride = Color.White;

                    if (info.FuelLeft.HasValue)
                    {
                        _fuelBar.Visible = true;
                        _fuelBar.Value = info.FuelLeft.Value;

                        if (info.FuelLeft.Value < 0.2f)
                            _fuelBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.Red };
                        else if (info.FuelLeft.Value < 0.5f)
                            _fuelBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.Orange };
                        else
                            _fuelBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.LimeGreen };

                        Disabled = false;
                    }
                    else
                    {
                        _fuelBar.Visible = false;
                        Disabled = false;
                    }
                }
            }
            else
            {
                var line1 = Loc.GetString("nuclear-reactor-slot-empty-line1", ("slot", SlotIndex + 1));
                var line2 = Loc.GetString("nuclear-reactor-slot-empty-line2");
                _textLabel.Text = $"{line1}\n{line2}";
                _textLabel.FontColorOverride = Color.White;
                _fuelBar.Visible = false;
                Disabled = true;
            }
        }
    }
}
