using System;
using System.Numerics;
using Content.Shared._BaroStation.NuclearReactor;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._BaroStation.NuclearReactor;

[GenerateTypedNameReferences]
public sealed partial class NuclearReactorWindow : DefaultWindow
{
    public event Action<bool>? ToggleReactor;
    public event Action<float>? SetTemperature;
    public event Action<int>? EjectRod;
    public event Action<int>? SetCoolingLevel;

    private readonly SlotButton[] _slotButtons = new SlotButton[4];
    private NuclearReactorUiState? _lastState;

    public NuclearReactorWindow()
    {
        RobustXamlLoader.Load(this);

        ToggleButton.OnPressed += _ => ToggleReactor?.Invoke(!(_lastState?.Enabled ?? false));

        SetTempButton.OnPressed += _ =>
        {
            if (float.TryParse(TargetTempInput.Text, out var temp))
                SetTemperature?.Invoke(temp);
        };

        CoolingDownButton.OnPressed += _ =>
        {
            var newLevel = (_lastState?.CoolingLevel ?? 1) - 1;
            if (newLevel >= 1)
                SetCoolingLevel?.Invoke(newLevel);
        };

        CoolingUpButton.OnPressed += _ =>
        {
            var newLevel = (_lastState?.CoolingLevel ?? 1) + 1;
            if (newLevel <= 8)
                SetCoolingLevel?.Invoke(newLevel);
        };

        for (int i = 0; i < 4; i++)
        {
            var btn = new SlotButton(i);
            btn.OnPressed += _ => EjectRod?.Invoke(btn.SlotIndex);
            _slotButtons[i] = btn;
            RodsGrid.AddChild(btn);
        }
    }

    public void UpdateState(NuclearReactorUiState state)
    {
        _lastState = state;

        if (state.Enabled)
        {
            StatusLabel.Text = Loc.GetString("nuclear-reactor-status-active");
            StatusLabel.SetOnlyStyleClass("LabelGood");
        }
        else
        {
            StatusLabel.Text = Loc.GetString("nuclear-reactor-status-inactive");
            StatusLabel.SetOnlyStyleClass("LabelDanger");
        }

        ToggleButton.Text = state.Enabled
            ? Loc.GetString("nuclear-reactor-window-toggle-off")
            : Loc.GetString("nuclear-reactor-window-toggle-on");
        TargetTempInput.Editable = !state.Enabled;
        SetTempButton.Disabled = state.Enabled;
        CoolingDownButton.Disabled = state.Enabled || state.CoolingLevel <= 1;
        CoolingUpButton.Disabled = state.Enabled || state.CoolingLevel >= 8;

        int activeRodCount = 0;
        foreach (var slot in state.RodSlots)
        {
            if (slot.HasItem && !slot.Depleted) activeRodCount++;
        }

        float rodOptimalTemp = activeRodCount * 1000f;
        OptimalTempLabel.Text = $"{rodOptimalTemp:F0} K";

        DepletedWarningLabel.Visible = state.HasDepletedRod;

        if (activeRodCount == 0)
        {
            StateLabel.Text = Loc.GetString("nuclear-reactor-mode-no-rods");
            StateLabel.SetOnlyStyleClass("LabelSecondaryColor");
        }
        else
        {
            float optimalTemp = state.OptimalTemperature;
            float optimalMin = optimalTemp - 300f;
            float optimalMax = optimalTemp + 300f;

            if (state.CurrentTemperature < optimalMin)
            {
                StateLabel.Text = Loc.GetString("nuclear-reactor-mode-insufficient", ("min", optimalMin));
                StateLabel.SetOnlyStyleClass("LabelCaution");
            }
            else if (state.CurrentTemperature > optimalMax)
            {
                StateLabel.Text = Loc.GetString("nuclear-reactor-mode-excessive", ("max", optimalMax));
                StateLabel.SetOnlyStyleClass("LabelDanger");
            }
            else
            {
                StateLabel.Text = Loc.GetString("nuclear-reactor-mode-optimal", ("min", optimalMin), ("max", optimalMax));
                StateLabel.SetOnlyStyleClass("LabelGood");
            }
        }

        TemperatureLabel.Text = $"{state.CurrentTemperature:F1} K";
        TemperatureBar.Value = state.CurrentTemperature;
        TemperatureBar.MaxValue = 30000;
        TargetTempInput.Text = state.TargetTemperature.ToString("F0");
        CoolingLevelLabel.Text = state.CoolingLevel.ToString();

        PowerLabel.Text = $"{state.PowerOutput / 1000f:F1} kW";

        IntegrityLabel.Text = $"{state.Integrity:F0}%";
        if (state.Integrity < 30)
            IntegrityLabel.SetOnlyStyleClass("LabelDanger");
        else if (state.Integrity < 60)
            IntegrityLabel.SetOnlyStyleClass("LabelCaution");
        else
            IntegrityLabel.SetOnlyStyleClass("LabelGood");

        for (int i = 0; i < 4; i++)
        {
            _slotButtons[i].UpdateState(state.RodSlots[i]);
        }

        WarningLabel.Visible = activeRodCount == 0;
    }

    private sealed class SlotButton : Button
    {
        public int SlotIndex { get; }
        private readonly Label _textLabel;
        private readonly ProgressBar _fuelBar;

        public SlotButton(int index)
        {
            SlotIndex = index;
            MinSize = new Vector2(100, 80);

            var vbox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center
            };

            _textLabel = new Label { Text = "Пусто", HorizontalAlignment = HAlignment.Center };
            _fuelBar = new ProgressBar
            {
                MinSize = new Vector2(80, 10),
                Visible = false,
                MinValue = 0,
                MaxValue = 1,
                Value = 0
            };

            vbox.AddChild(_textLabel);
            vbox.AddChild(_fuelBar);
            AddChild(vbox);
        }

        public void UpdateState(ContainerInfo info)
        {
            if (info.HasItem)
            {
                if (info.Depleted)
                {
                    _textLabel.Text = info.ItemName ?? "Стержень";
                    _textLabel.FontColorOverride = Color.Red;
                    _fuelBar.Visible = true;
                    _fuelBar.Value = 0;
                    _fuelBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.Gray };
                    Disabled = false;
                }
                else
                {
                    _textLabel.Text = info.ItemName ?? "Стержень";
                    _textLabel.FontColorOverride = Color.White;

                    if (info.FuelLeft.HasValue)
                    {
                        _fuelBar.Visible = true;
                        _fuelBar.Value = info.FuelLeft.Value;

                        if (info.FuelLeft.Value < 0.2f)
                            _fuelBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.Red };
                        else if (info.FuelLeft.Value < 0.5f)
                            _fuelBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.Orange };
                        else
                            _fuelBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.LimeGreen };

                        Disabled = false;
                    }
                    else
                    {
                        _fuelBar.Visible = false;
                        Disabled = false;
                    }
                }

                _fuelBar.InvalidateMeasure();
                _fuelBar.InvalidateArrange();
            }
            else
            {
                _textLabel.Text = $"Слот {SlotIndex + 1}\n(Пусто)";
                _textLabel.FontColorOverride = Color.White;
                _fuelBar.Visible = false;
                Disabled = true;
            }
        }
    }
}
