using Content.Client.Resources;
using Content.Client.UserInterface.Controls;
using Content.Shared._BaroStation.Achievements;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Log;
using Robust.Shared.Utility;

namespace Content.Client._BaroStation.Achievements;

[GenerateTypedNameReferences]
public sealed partial class AchievementEntryControl : BoxContainer
{
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    private ISawmill _sawmill = default!;

    public string AchievementId { get; private set; } = string.Empty;
    public bool IsEarned { get; private set; }

    public AchievementEntryControl(AchievementPrototype prototype, bool isEarned)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sawmill = Logger.GetSawmill("achievements.ui");

        AchievementId = prototype.ID;
        IsEarned = isEarned;

        TitleLabel.Text = Loc.GetString(prototype.Name);
        DescriptionLabel.Text = Loc.GetString(prototype.Description);

        // Убеждаемся, что элементы видимы
        TitleLabel.Visible = true;
        DescriptionLabel.Visible = true;

        // Стиль для выполненных и невыполненных достижений
        if (isEarned)
        {
            Modulate = new Color(200, 200, 200);
            ToolTip = "Earned!";
            AddStyleClass("AchievementEarned");
        }
        else
        {
            Modulate = new Color(100, 100, 100, 180); // Полупрозрачный
            ToolTip = "Not yet earned";
            AddStyleClass("AchievementLocked");
        }

        _sawmill.Info($"Created entry for {prototype.ID}, isEarned={isEarned}");
    }
}
