using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._BaroStation.Achievements;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.GameObjects;
using Robust.Shared.Log;

namespace Content.Client._BaroStation.Achievements;

[GenerateTypedNameReferences]
public sealed partial class AchievementsWindow : FancyWindow
{
    private readonly IEntityManager _entityManager;
    private readonly ISawmill _sawmill;

    private List<AchievementPrototype> _cachedAllAchievements = new();
    private HashSet<string> _cachedEarnedIds = new();
    private bool _hasCachedData;

    public AchievementsWindow()
    {
        RobustXamlLoader.Load(this);
        _entityManager = IoCManager.Resolve<IEntityManager>();
        _sawmill = Logger.GetSawmill("achievements");
    }

    public bool IsDisposed => Disposed;

    public void CacheAchievements(List<AchievementPrototype> allAchievements, HashSet<string> earnedIds)
    {
        _cachedAllAchievements = allAchievements;
        _cachedEarnedIds = earnedIds;
        _hasCachedData = true;

        _sawmill.Info($"Cached achievements: {allAchievements.Count} total, {earnedIds.Count} earned");
    }

    public void UpdateAchievements(List<AchievementPrototype> allAchievements, HashSet<string> earnedIds)
    {
        _sawmill.Info($"UpdateAchievements called: Total={allAchievements.Count}, Earned={earnedIds.Count}, IsOpen={IsOpen}");
        ClearList(EarnedList);
        ClearList(LockedList);

        if (allAchievements.Count == 0)
        {
            _sawmill.Warning("No achievements found in prototypes!");
            StatsLabel.Text = "No achievements found";
            return;
        }
        var earnedCount = earnedIds.Count;
        StatsLabel.Text = $"Achievements: {earnedCount} / {allAchievements.Count}";

        var earnedAchievements = new List<AchievementPrototype>();
        var lockedAchievements = new List<AchievementPrototype>();

        foreach (var proto in allAchievements)
        {
            if (earnedIds.Contains(proto.ID))
                earnedAchievements.Add(proto);
            else
                lockedAchievements.Add(proto);
        }

        _sawmill.Info($"Earned: {earnedAchievements.Count}, Locked: {lockedAchievements.Count}");

        EarnedHeader.Visible = earnedAchievements.Any();
        LockedHeader.Visible = lockedAchievements.Any();
        Separator.Visible = earnedAchievements.Any() && lockedAchievements.Any();

        foreach (var proto in earnedAchievements)
        {
            var entry = new AchievementEntryControl(proto, true);
            EarnedList.AddChild(entry);
            _sawmill.Debug($"Added earned achievement: {proto.ID}");
        }
        foreach (var proto in lockedAchievements)
        {
            var entry = new AchievementEntryControl(proto, false);
            LockedList.AddChild(entry);
            _sawmill.Debug($"Added locked achievement: {proto.ID}");
        }

        _sawmill.Info($"Displayed {earnedAchievements.Count} earned and {lockedAchievements.Count} locked achievements");
        _sawmill.Info($"EarnedList children: {EarnedList.ChildCount}, LockedList children: {LockedList.ChildCount}");
    }

    protected override void Opened()
    {
        base.Opened();
        _sawmill.Info("Window opened");

        if (_hasCachedData)
        {
            _sawmill.Info("Using cached data");
            UpdateAchievements(_cachedAllAchievements, _cachedEarnedIds);
        }
        else
        {
            _sawmill.Info("No cached data, waiting for server response");
            StatsLabel.Text = "Loading achievements...";
        }
    }

    private void ClearList(BoxContainer list)
    {
        var children = list.Children.ToList();
        foreach (var child in children)
        {
            list.RemoveChild(child);
            child.Dispose();
        }
    }
}
